### ISSUE TITLE
Hugging Face Spaces version

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [FrancescoSaverioZuppichini/my-spaces#1]
Need to figure it out the version of common packages (e.g. `ffmepg`) using on hugging face spaces

**Comment by AntreasAntoniou** [comment]
Have you been able to make any progress on this? While I don't work at huggingface, I have interacted with them quite a bit, and could try to bring this to their attention if no progress has been made.

**Comment by FrancescoSaverioZuppichini** [comment]
> Have you been able to make any progress on this? While I don't work at huggingface, I have interacted with them quite a bit, and could try to bring this to their attention if no progress has been made.

Yeah, I've asked them several times but they don't seem to care about it while claiming to be as open as possible - fell free to try, I won't interact with them anymore since they made it legally unwise for me to do so

Will close it for now - and for the record, they could just allow you to download the image 

Thanks a lot for commenting <3

**Comment by osanseviero** [comment]
Spaces allows running locally with Docker. Just click at top right, "Run with Docker" (since March). See https://www.docker.com/blog/docker-and-hugging-face-partner-to-democratize-ai/
