### ISSUE TITLE
Running on docker desktop

### ISSUE THREAD

**Issue by b1ek** [FrancescoSaverioZuppichini/my-spaces#8]
To run this on docker desktop, do it like this:
```bash
export HUGGING_FACE_HUB_TOKEN=<YOUR_HUGGING_FACE_HUB_TOKEN>
export DOCKER_HOST=unix:///home/$(whoami)/.docker/desktop/docker.sock # this does the magic
my-spaces run https://huggingface.co/spaces/Francesco/stable-diffusion
```

I would appreciate if it would be added to README.md

**Comment by FrancescoSaverioZuppichini** [comment]
Thanks a lot <3 Would you like to PR it?

**Comment by b1ek** [comment]
> Thanks a lot <3 Would you like to PR it?

no, sorry. i currently don't have time for this.

to be honest, i dont even remember what is this issue about in the first place

**Comment by FrancescoSaverioZuppichini** [comment]
> > Thanks a lot <3 Would you like to PR it?
> 
> no, sorry. i currently don't have time for this.
> 
> to be honest, i dont even remember what is this issue about in the first place

then, let's close it :)
